### ISSUE TITLE
terser compress the code and breaks it

### ISSUE THREAD

**Issue by kopax** [expo/snack-web#35]
I am having trouble with snack being different than my current expo project that use:

```
└─┬ @expo/webpack-config@0.11.1
  └─┬ terser-webpack-plugin@1.4.3
    └── terser@4.6.3 
```

For some reason, the minification is breaking the web app when used on snack.expo.io

As an example https://snack.expo.io/@kopax/restless-turkish-delight

**Comment by IjzerenHein** [comment]
Hi! I'm sorry this repository has not been maintained for some time. We have just moved the Snack web app to the new Snack monorepo at https://github.com/expo/snack

Snack will definitely result in different outputs as your regular Expo build will. This is largely due to the fact that packages are bundled by an external bundler and dynamically combined to run as a single app the Snack runtime.

If you are still experiencing issues  then please report these in the new https://github.com/expo/snack repository monorepo.
The `expo/snack-web` repo will be archived.
