### ISSUE TITLE
can't import v36 expo?

### ISSUE THREAD

**Issue by gpbaculio** [expo/snack-web#40]
this is my repo: https://github.com/gpbaculio/cs50project3.git

i've imported git repos until i updated my expo, help?

**Comment by IjzerenHein** [comment]
Hi! 👋 
I was able to successfully import your repo. However it does show a lot of errors and warnings. You might need to address those or upgrade to a more recent SDK in order to get your project to work.

https://snack.expo.io/@git/github.com/gpbaculio/cs50project3

![image](https://user-images.githubusercontent.com/6184593/96988498-b2efd480-1524-11eb-95cd-4d69d5f02696.png)
